// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qbynezcearzawrieibvf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFieW5lemNlYXJ6YXdyaWVpYnZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NDgzMDQsImV4cCI6MjA3MzMyNDMwNH0.nckHEO3j0riRKjN8Ph8cPXn6jx7dhfLVA6sJo17hkD0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});